### ISSUE TITLE
Installation error " file failed to open for reading (No such file or directory):"

### ISSUE THREAD

**Issue by nengc** [Koromix/koffi#58]
Hi, when i install koffi in my Linux OS,  some fatal error occurred.

![image](https://github.com/Koromix/koffi/assets/19792047/25ab4e04-d715-49c7-a63a-95a5f2cbabf4)

**Comment by Koromix** [comment]
Looks like an old Linux distribution given that it is using GCC 5.4.0.
Which OS is it? what version?

**Comment by nengc** [comment]
The kernel is 4.4.131-20210525
and the arch is aarch64
gcc version 5.4.0
cmake version 3.27.1

**Comment by Koromix** [comment]
This specific bug has been fixed in Koffi 2.5.10 :)

**Comment by nengc** [comment]
Hi @Koromix ,thank you for your reply rapidly. But seems still have problems.
![image](https://github.com/Koromix/koffi/assets/19792047/305c5aea-4dc0-4e99-9e29-d7ab228a23e0)
![image](https://github.com/Koromix/koffi/assets/19792047/126c4b3c-c303-4fa7-b6cf-fe05351f9605)

**Comment by nengc** [comment]
Thanks, it works well after i upgraded my gcc.
